<?php require 'templates/header.phtml' ?>

<h1>Categorías de productos</h1>

<ul>
<?php foreach($categorias as $categoria): ?>
    <li>
        <a href="<?= BASE_URL ?>categoria/<?= urlencode($categoria->nombre) ?>"><?= $categoria->nombre ?></a>
    </li>
<?php endforeach ?>
</ul>

<?php if (isset($categoriaActual)): ?>
    <h2>Estás viendo la categoría: <?= $categoriaActual ?></h2>
<?php else : ?>
    <h1>Productos</h1>
<?php endif; ?>

<ul>
<?php foreach($products as $product): ?>
    <li>
        <a href="<?= BASE_URL ?>producto/<?= urlencode($product->nombre) ?>"><?= $product->nombre ?></a>
    </li>
<?php endforeach ?>
</ul>

<?php require 'templates/footer.phtml' ?>